checksumBehavior: throw

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

# for safety, restrict installing recently released packages
npmMinimalAgeGate: 1440