services:
  localstack:
    image: localstack/localstack:4.12
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,sqs,lambda,apigateway,cloudformation,ssm,iam
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - localstack-data:/var/lib/localstack
      - ./localstack/init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  localstack-data:
